planeta(tierra).
planeta(mercurio).
planeta(venus).
planeta(marte).
planeta(jupiter).
planeta(saturno).
planeta(urano).
planeta(neptuno).

planetoide(pluton).

estrella(sol).

/*luna de la tierra*/
luna(luna).
/*lunas de marte*/
luna(fobos).
luna(deimos).
/*lunas de jupiter*/
luna(io).
luna(europa).
luna(ganimedes).
luna(calisto).
luna(amaltea).
luna(himalia).
luna(elara).
luna(pasiphae).
luna(sinope).
luna(lysithea).
luna(carme).
luna(ananke).
luna(leda).
luna(thebe).
luna(adrastea).
luna(metis).
luna(callirrhoe).
luna(temisto).
luna(megaclite).
luna(taigete).
luna(caldona).
luna(harpalice).
luna(calice).
luna(yocasta).
luna(erinome).
luna(isonoe).
luna(praxidice).
luna(autonoe).
luna(tione).
luna(hermipe).
luna(aitne).
luna(euridome).
luna(euanthe).
luna(euporia).
luna(ortosia).
luna(esponde).
luna(cale).
luna(pasitea).
luna(hegemone).
luna(mnemea).
luna(aedea).
luna(telxinoe).
luna(arce).
luna(kallichore).
luna(helike).
luna(carpo).
luna(eukelade).
luna(cliene).
luna(kore).
luna(herse).
luna(dia).
luna(eirene).
luna(filofrosine).
luna(eufreme).
luna(valetudo).
luna(pandia).
luna(ersa).

/*lunas de saturno*/
luna(mimas). 
luna(encelado). 
luna(tetis). 
luna(dione). 
luna(rea).
luna(titan).
luna(hiperion).
luna(japeto).
luna(febe).
luna(jano).
luna(epimeteo).
luna(helena).
luna(telesto).
luna(calipso).
luna(atlas).
luna(prometeo).
luna(pandora).
luna(pan).
luna(ymir).
luna(paaliaq).
luna(tarvos).
luna(ijiraq).
luna(suttungr).
luna(kiviuk).
luna(mundilfari).
luna(albiorix).
luna(skadi).
luna(erriapo).
luna(siarnaq).
luna(thrymr).
luna(narvi).
luna(metone).
luna(palene).
luna(pollux).
luna(dafne).
luna(aegir).
luna(bebhionn).
luna(bergelmir).
luna(bestla).
luna(farbauti).
luna(fenrir).
luna(fornjot).
luna(hati).
luna(hyrrokkin).
luna(kari).
luna(loge).
luna(skoll).
luna(surtur).
luna(anthe).
luna(jarnsaxa).
luna(greip).
luna(tarqeq).
luna(aegaeon).

/*lunas de urano*/
luna(ariel).
luna(umbriel).
luna(titania).
luna(oberon).
luna(miranda).
luna(cordelia).
luna(ofelia).
luna(blanca).
luna(cresida).
luna(desdemona).
luna(julieta).
luna(porcia).
luna(rosalinda).
luna(belinda).
luna(puck).
luna(caliban).
luna(sycorax).
luna(prospero).
luna(setebos).
luna(stefano).
luna(trinculo).
luna(francisco).
luna(margarita).
luna(ferdinando).
luna(perdita).
luna(mab).
luna(cupido).
/*lunas de neptuno*/
luna(triton).
luna(nereida).
luna(nayade).
luna(talasa).
luna(despina).
luna(galatea).
luna(larisa).
luna(proteo).
luna(halimede).
luna(psamathe).
luna(sao).
luna(laomedeia).
luna(neso).

planetade(tierra, luna).

planetade(marte,fobos).
planetade(marte,deimos).

planetade(jupiter,io).
planetade(jupiter,europa).
planetade(jupiter,ganimedes).
planetade(jupiter,calisto).
planetade(jupiter,amaltea).
planetade(jupiter,himalia).
planetade(jupiter,elara).
planetade(jupiter,pasiphae).
planetade(jupiter,sinope).
planetade(jupiter,lysithea).
planetade(jupiter,carme).
planetade(jupiter,ananke).
planetade(jupiter,leda).
planetade(jupiter,thebe).
planetade(jupiter,adrastea).
planetade(jupiter,metis).
planetade(jupiter,callirrhoe).
planetade(jupiter,temisto).
planetade(jupiter,megaclite).
planetade(jupiter,taigete).
planetade(jupiter,caldona).
planetade(jupiter,harpalice).
planetade(jupiter,calice).
planetade(jupiter,yocasta).
planetade(jupiter,erinome).
planetade(jupiter,isonoe).
planetade(jupiter,praxidice).
planetade(jupiter,autonoe).
planetade(jupiter,tione).
planetade(jupiter,hermipe).
planetade(jupiter,aitne).
planetade(jupiter,euridome).
planetade(jupiter,euanthe).
planetade(jupiter,euporia).
planetade(jupiter,ortosia).
planetade(jupiter,esponde).
planetade(jupiter,cale).
planetade(jupiter,pasitea).
planetade(jupiter,hegemone).
planetade(jupiter,mnemea).
planetade(jupiter,aedea).
planetade(jupiter,telxinoe).
planetade(jupiter,arce).
planetade(jupiter,kallichore).
planetade(jupiter,helike).
planetade(jupiter,carpo).
planetade(jupiter,eukelade).
planetade(jupiter,cliene).
planetade(jupiter,kore).
planetade(jupiter,herse).
planetade(jupiter,dia).
planetade(jupiter,eirene).
planetade(jupiter,filofrosine).
planetade(jupiter,eufreme).
planetade(jupiter,valetudo).
planetade(jupiter,pandia).
planetade(jupiter,ersa).

planetade(saturno,mimas). 
planetade(saturno,encelado). 
planetade(saturno,tetis). 
planetade(saturno,dione). 
planetade(saturno,rea).
planetade(saturno,titan).
planetade(saturno,hiperion).
planetade(saturno,japeto).
planetade(saturno,febe).
planetade(saturno,jano).
planetade(saturno,epimeteo).
planetade(saturno,helena).
planetade(saturno,telesto).
planetade(saturno,calipso).
planetade(saturno,atlas).
planetade(saturno,prometeo).
planetade(saturno,pandora).
planetade(saturno,pan).
planetade(saturno,ymir).
planetade(saturno,paaliaq).
planetade(saturno,tarvos).
planetade(saturno,ijiraq).
planetade(saturno,suttungr).
planetade(saturno,kiviuk).
planetade(saturno,mundilfari).
planetade(saturno,albiorix).
planetade(saturno,skadi).
planetade(saturno,erriapo).
planetade(saturno,siarnaq).
planetade(saturno,thrymr).
planetade(saturno,narvi).
planetade(saturno,metone).
planetade(saturno,palene).
planetade(saturno,pollux).
planetade(saturno,dafne).
planetade(saturno,aegir).
planetade(saturno,bebhionn).
planetade(saturno,bergelmir).
planetade(saturno,bestla).
planetade(saturno,farbauti).
planetade(saturno,fenrir).
planetade(saturno,fornjot).
planetade(saturno,hati).
planetade(saturno,hyrrokkin).
planetade(saturno,kari).
planetade(saturno,loge).
planetade(saturno,skoll).
planetade(saturno,surtur).
planetade(saturno,anthe).
planetade(saturno,jarnsaxa).
planetade(saturno,greip).
planetade(saturno,tarqeq).
planetade(saturno,aegaeon).

planetade(urano,ariel).
planetade(urano,umbriel).
planetade(urano,titania).
planetade(urano,oberon).
planetade(urano,miranda).
planetade(urano,cordelia).
planetade(urano,ofelia).
planetade(urano,blanca).
planetade(urano,cresida).
planetade(urano,desdemona).
planetade(urano,julieta).
planetade(urano,porcia).
planetade(urano,rosalinda).
planetade(urano,belinda).
planetade(urano,puck).
planetade(urano,caliban).
planetade(urano,sycorax).
planetade(urano,prospero).
planetade(urano,setebos).
planetade(urano,stefano).
planetade(urano,trinculo).
planetade(urano,francisco).
planetade(urano,margarita).
planetade(urano,ferdinando).
planetade(urano,perdita).
planetade(urano,mab).
planetade(urano,cupido).

planetade(neptuno,triton).
planetade(neptuno,nereida).
planetade(neptuno,nayade).
planetade(neptuno,talasa).
planetade(neptuno,despina).
planetade(neptuno,galatea).
planetade(neptuno,larisa).
planetade(neptuno,proteo).
planetade(neptuno,halimede).
planetade(neptuno,psamathe).
planetade(neptuno,sao).
planetade(neptuno,laomedeia).
planetade(neptuno,neso).

size([],0).
size([X|Y],N):-size(Y,N1),N is N1+1.

/*
rotar(X,X,0).
rotar([X|Y],L,N):-N1 is N-1, append(Y,[X],Y1),rotar(Y1,L,N1).*/

rotar(L,R,N):-append(X,Y,L),size(X,N).








